Host galaxy3
    HostName cluster.seoklab.org
    Port 1022
    ControlPersist 0

Host galaxy4
    ProxyJump galaxy3
    ControlPersist 10m

Host galaxy*
    ControlPath ~/.ssh/control-%L-%r@%h:%p
    ControlMaster auto
